export const TEMPLATES = [
    {
        id: "673df73590b60e5a4806e681",
        name: "Modern Minimalist",
        role: "Software Dev",
        experience: "Entry Level",
        company: "Google",
        color: "bg-slate-100",
        accent: "bg-slate-900",
    },
    {
        id: "673df73590b60e5a4806e682",
        name: "Professional Corp",
        role: "Backend",
        experience: "Senior",
        company: "Microsoft",
        color: "bg-blue-50",
        accent: "bg-blue-600",
    },
    {
        id: "673df73590b60e5a4806e683",
        name: "Creative Studio",
        role: "Frontend",
        experience: "Mid Level",
        company: "Startup",
        color: "bg-purple-50",
        accent: "bg-purple-600",
    },
    {
        id: "673df73590b60e5a4806e684",
        name: "Tech Lead",
        role: "Fullstack",
        experience: "Lead",
        company: "Amazon",
        color: "bg-emerald-50",
        accent: "bg-emerald-600",
    },
    {
        id: "673df73590b60e5a4806e685",
        name: "Simple Clean",
        role: "Software Dev",
        experience: "Entry Level",
        company: "Meta",
        color: "bg-gray-50",
        accent: "bg-gray-800",
    },
    {
        id: "673df73590b60e5a4806e686",
        name: "Executive",
        role: "Management",
        experience: "Executive",
        company: "Netflix",
        color: "bg-zinc-100",
        accent: "bg-zinc-900",
    },
    ...Array.from({ length: 10 }).map((_, i) => ({
        id: `673df73590b60e5a4806e6${87 + i}`,
        name: `Template ${i + 1}`,
        role: ["Software Dev", "Frontend", "Backend"][i % 3],
        experience: ["Entry Level", "Mid Level", "Senior"][i % 3],
        company: ["Google", "Microsoft", "Startup"][i % 3],
        color: ["bg-red-50", "bg-orange-50", "bg-indigo-50"][i % 3],
        accent: ["bg-red-600", "bg-orange-600", "bg-indigo-600"][i % 3],
    })),
];

export const ROLES = [
    "Software Dev",
    "Frontend",
    "Backend",
    "Fullstack",
    "Management",
];

export const EXPERIENCE = [
    "Entry Level",
    "Mid Level",
    "Senior",
    "Lead",
    "Executive",
];

export const COMPANIES = [
    "Google",
    "Microsoft",
    "Startup",
    "Amazon",
    "Meta",
    "Netflix",
    "Test 1",
    "Test 2",
    "Test 3",
    "Test 4",
    "Test 5",
    "Test 6",
    "Test 7",
    "Test 8",
    "Test 9",
];
